{
 "title": "ArgoCD Operational Dashboard",
 "description": "Monitors operational metrics of the ArgoCD platform, including API server performance, repository syncing, and controller activities.",
 "tags": [
  "Kubernetes",
  "argo-cd"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(argocd_app_info{}, namespace)"
   },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\"}, dest_server)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$cluster\"}, project)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_cluster_info{kubernetes_namespace=~'$namespace', job=~'$job'})"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(argocd_app_info{namespace=~'$namespace', job=~'$job'}) by (repo))"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project'})"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project'}) by (job, dest_server, project, name, health_status, sync_status)"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project'}) by (health_status)",
     "legendFormat": "{{ health_status }}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project'}) by (sync_status)",
     "legendFormat": "{{ sync_status }}"
    }
   ]
  },
  { "title": "Sync Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Sync Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project'}[$__rate_interval]))) by (job, dest_server, project, name)",
     "legendFormat": "{{ dest_server }}/{{ project }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project', phase=~\"Error|Failed\"}[$__rate_interval]))) by (job, dest_server, project, application, phase)",
     "legendFormat": "{{ dest_server }}/{{ project }}/{{ application }} - {{ phase }}"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Recociliation Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_reconcile_count{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster'}[$__rate_interval]))) by (namespace, job, dest_server)",
     "legendFormat": "{{ namespace }}/{{ dest_server }}"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_bucket{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster'}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K8s API Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_k8s_request_total{namespace=~'$namespace', job=~'$job', project=~'$project'}[$__rate_interval]))) by (job, server, project, verb, resource_kind)",
     "legendFormat": "{{ server }}/{{ project }} - {{ verb }}/{{ resource_kind }}"
    }
   ]
  },
  {
   "title": "Pending Kubectl Runs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_kubectl_exec_pending{kubernetes_namespace=~'$namespace', job=~'$job'}) by (job, command)",
     "legendFormat": "{{ dest_server }} - {{ command }}"
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Resource Objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_cluster_api_resource_objects{kubernetes_namespace=~'$namespace', job=~'$job', server=~'$cluster'}) by (namespace, job, server)",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "API Resources",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_cluster_api_resources{kubernetes_namespace=~'$namespace', job=~'$job', server=~'$cluster'}) by (namespace, job, server)",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Cluster Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_cluster_events_total{kubernetes_namespace=~'$namespace', job=~'$job', server=~'$cluster'}[$__rate_interval])) by (namespace, job, server)",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  { "title": "Repo Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Git Requests (ls-remote)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{kubernetes_namespace=~'$namespace', job=~'$job', request_type=\"ls-remote\"}[$__rate_interval])) by (namespace, job, repo)",
     "legendFormat": "{{ namespace }} - {{ repo }}"
    }
   ]
  },
  {
   "title": "Git Requests (checkout)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_total{kubernetes_namespace=~'$namespace', job=~'$job', request_type=\"fetch\"}[$__rate_interval])) by (namespace, job, repo)",
     "legendFormat": "{{ namespace }} - {{ repo }}"
    }
   ]
  },
  {
   "title": "Git Fetch Performance",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{kubernetes_namespace=~'$namespace', job=~'$job', request_type=\"fetch\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Git Ls-remote Performance",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{kubernetes_namespace=~'$namespace', job=~'$job', request_type=\"ls-remote\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}