{
 "title": "ArgoCD Applications Dashboard",
 "description": "Provides insights into the health, sync status, and metrics of ArgoCD-managed applications, helping monitor their state and performance over time.",
 "tags": [
  "Kubernetes",
  "argo-cd"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(argocd_app_info{}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\"}, dest_server)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$cluster\"}, project)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$cluster\", project=~\"$project\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Summary by Cluster, Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application Health Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project'}) by (job, dest_server, project, health_status)",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ health_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project'}) by (job, dest_server, project, sync_status)",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ sync_status }}"
    }
   ]
  },
  {
   "title": "Application Syncs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project'}[$__rate_interval]))) by (job, dest_server, project, phase)",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ phase }}"
    }
   ]
  },
  {
   "title": "Application Auto Sync Enabled",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project'}) by (job, dest_server, project, autosync_enabled)",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ autosync_enabled }}"
    }
   ]
  },
  {
   "title": "Applications (Unhealthy/OutOfSync/AutoSyncDisabled) Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Applications Unhealthy",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project', health_status!~\"Healthy|Progressing\"}) by (job, dest_server, project, name, health_status)"
    }
   ]
  },
  {
   "title": "Applications Out Of Sync",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project', sync_status!=\"Synced\"}) by (job, dest_server, project, name, sync_status) > 0"
    }
   ]
  },
  {
   "title": "Applications That Failed to Sync[7d]",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project', phase!=\"Succeeded\"}[7d]))) by (job, dest_server, project, name, phase) > 0"
    }
   ]
  },
  {
   "title": "Applications With Auto Sync Disabled",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project', autosync_enabled!=\"true\"}) by (job, dest_server, project, name, autosync_enabled) > 0"
    }
   ]
  },
  { "title": "Application ($application)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Application Health Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project', name=~'$application'}) by (namespace, job, dest_server, project, name, health_status)",
     "legendFormat": "{{ dest_server }}/{{ project }}/{{ name }} - {{ health_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project', name=~'$application'}) by (namespace, job, dest_server, project, name, sync_status)",
     "legendFormat": "{{ dest_server }}/{{ project }}/{{ name }} - {{ sync_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Result",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{namespace=~'$namespace', job=~'$job', dest_server=~'$cluster', project=~'$project', name=~'$application'}[$__rate_interval]))) by (namespace, job, dest_server, project, name, phase)",
     "legendFormat": "{{ dest_server }}/{{ project }}/{{ name }} - {{ phase }}"
    }
   ]
  }
 ]
}