{
 "title": "Histogram dashboard",
 "tags": [ "spam" ],
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "random_histogram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sum with le = 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_histogram_bucket{le=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum with le = 5",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_histogram_bucket{le=\"5\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum with le = 10",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_histogram_bucket{le=\"10\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Sum",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(random_histogram_sum)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average count over 1h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(random_histogram_count[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ordered_histogram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sum with le = 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ordered_histogram_bucket{le=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum with le = 5",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ordered_histogram_bucket{le=\"5\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum with le = 10",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ordered_histogram_bucket{le=\"10\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Sum",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ordered_histogram_sum)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average count over 1h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ordered_histogram_count[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}