{
 "title": "Random Gauge Dashboard",
 "tags": [ "spam" ],
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(random_gauge_1,country)"
    }
   },
   {
    "name": "platform",
    "label": "Platform",
    "query": {
     "query": "label_values(random_gauge_1,platform)"
    }
   }
  ]
 },
 "panels": [
  { "title": "random_gauge_1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Active Sessions",
   "type": "stat",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_gauge_1{country=~\"$country\", platform=~\"$platform\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions by Platform",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 10, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_gauge_1{country=~\"$country\"}) by (platform)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions by Country",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_gauge_1{platform=~\"$platform\"}) by (country)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "random_gauge_2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Active Sessions",
   "type": "stat",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_gauge_2{country=~\"$country\", platform=~\"$platform\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions by Platform",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 10, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_gauge_2{country=~\"$country\"}) by (platform)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions by Country",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_gauge_2{platform=~\"$platform\"}) by (country)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total Active Sessions",
   "type": "stat",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_gauge_3{country=~\"$country\", platform=~\"$platform\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions by Platform",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 10, "x": 5, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_gauge_3{country=~\"$country\"}) by (platform)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions by Country",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(random_gauge_3{platform=~\"$platform\"}) by (country)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}