global:
  additionalLabels:
    managed_by: argo-cd
controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
dex:
  enabled: false
redis:
  enabled: true
server:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
repoServer:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
applicationSet:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
notifications:
  enabled: false
